### PR TITLE
Fix weapon slot positioning

### LINKED ISSUE #52: Default Weapon Slot Positioning
Fix hook point positions

### PR DESCRIPTION
**Pull request by Swxer**

### CODE REVIEW

File: Assets/Scripts/Loadout/LoadoutStation.cs [hunk 1]
```diff
@@ -33,9 +37,20 @@ private void OnTriggerExit2D(Collider2D other)
...
+
+        private void DisableBodyController()
+        {
+            _playerBody.enabled = false;
+        }
+
+        private void EnableBodyController()
+        {
+            _playerBody.enabled = true;
+        }
```
Comment (mattlau1) [inline Assets/Scripts/Loadout/LoadoutStation.cs]: Instead of getting another reference to the player body, I thiink it will be cleaner to just do 
`other.GetComponent<PlayerBodyController>()` inside of the OnTrigger methods.

This keeps the data source coming from 1 place (single source of truth)

File: Assets/Scripts/Player/PlayerItemSlotPosition.cs [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+
+    private static void SetTransform(Transform slot, Vector2 pos, float rot)
+    {
+        slot.localPosition = pos;
+        slot.localRotation = Quaternion.Euler(0, 0, rot);
+    }
+
+    private static void SetSlotSortingGroup(Transform slot, int order)
+    {
+        var sortingGroup = slot.GetComponent<SortingGroup>();
```
Comment (mattlau1) [inline Assets/Scripts/Player/PlayerItemSlotPosition.cs]: Cache all of the sorting groups in Awake instead of doing a GetComponent every single Update call

File: Assets/Scripts/Loadout/ItemFormationData.cs [hunk 3]
```diff
@@ -0,0 +1,83 @@
...
+            Middle = m;
+            FrontLeftLayer = FrontRightLayer = BackLeftLayer = BackRightLayer = TailLayer = MiddleLayer = layer;
+            FrontLeftRot = FrontRightRot = BackLeftRot = BackRightRot = TailRot = MiddleRot = 0;
+        }
+    }
+
+    [Header("Directional Formations")] public SlotGroup UpPositions;
+    public SlotGroup DownPositions;
+    public SlotGroup LeftPositions;
+    public SlotGroup RightPositions;
```
Comment (mattlau1) [inline Assets/Scripts/Loadout/ItemFormationData.cs]: Restrict the setter to private by chagning these to properties. The general advice is to always be as restrictive as possible. Your setter should not be exposed to other classes or else they can mutate this (e.g. set it to null) and break other code.

File: Assets/Scripts/Loadout/ItemFormationData.cs [hunk 4]
```diff
@@ -0,0 +1,83 @@
+using UnityEngine;
+
+[CreateAssetMenu(fileName = "RobotFormationData", menuName = "Robot/Formation Data")]
+public class ItemFormationData : ScriptableObject
+{
+    [System.Serializable]
+    public class SlotGroup
```
Comment (mattlau1) [inline Assets/Scripts/Loadout/ItemFormationData.cs]: Can this be a struct

**Review by mattlau1 — CHANGES_REQUESTED** [review]

File: Assets/Scripts/Loadout/ItemFormationData.cs (hunk 4 above)
Comment (mattlau1) [reply Assets/Scripts/Loadout/ItemFormationData.cs]: You generally use structs are generally used to represent 'data objects' by convention

They are also more performant because they are allocated on the stack rather than the heap

File: Assets/Scripts/Player/PlayerItemSlotPosition.cs [hunk 5]
```diff
@@ -0,0 +1,97 @@
...
+    private SortingGroup _middleSorting;
+
+    private void Awake()
+    {
+        _frontLeftSorting = _frontLeftSlot.GetComponent<SortingGroup>();
+        _frontRightSorting = _frontRightSlot.GetComponent<SortingGroup>();
+        _backLeftSorting = _backLeftSlot.GetComponent<SortingGroup>();
+        _backRightSorting = _backRightSlot.GetComponent<SortingGroup>();
+        _tailSorting = _tailSlot.GetComponent<SortingGroup>();
+        _middleSorting = _middleSlot.GetComponent<SortingGroup>();
```
Comment (mattlau1) [inline Assets/Scripts/Player/PlayerItemSlotPosition.cs]: Use serializefield instead fo getcomponent

**Review by mattlau1 — CHANGES_REQUESTED** [review]

**Review by mattlau1 — APPROVED** [review]
